# 固有値・固有ベクトル

https://python.atelierkobato.com/diagonalization/
    
https://techacademy.jp/magazine/19190   

In [2]:
import numpy as np

In [11]:
def eig_diag(x):
    eig = np.linalg.eig(x)
    e = np.diag(eig[0])
    p = eig[1]
    return e, p

In [7]:
X = [[5, 2], [2, 5]]

固有値と固有ベクター

In [26]:
e, p = np.linalg.eigh(X)
print(e)
print(p)

[3. 7.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [27]:
#p = p/np.sqrt(2)
print(p)
pi = np.linalg.inv(p)
print(pi)

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


対角成分

In [15]:
np.diag(e)

array([[7., 0.],
       [0., 3.]])

In [28]:
np.dot(np.dot(pi,X),p)

array([[3.00000000e+00, 4.80650139e-17],
       [1.37549587e-16, 7.00000000e+00]])

In [22]:
np.dot(pi,np.dot(X,p))

array([[7.00000000e+00, 6.66133815e-16],
       [1.11022302e-15, 3.00000000e+00]])

In [12]:
eig_diag(X)

(array([[7., 0.],
        [0., 3.]]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [1]:
a = [[1, 1], [1, -1]]

In [3]:
b = np.linalg.inv(a)
print(b)

[[ 0.5  0.5]
 [ 0.5 -0.5]]


In [6]:
c = b*2

In [8]:
Y = b*X*a
Y

array([[2.5, 1. ],
       [1. , 2.5]])

In [35]:
import numpy as np
 
# 例題の行列
A = np.array([[3, 0],
              [1, 2]])
 
# 固有値と固有ベクトルを求める。
eig, P = np.linalg.eig(A)
print(eig)
print(P)
 
# 対角化
D = np.dot(np.dot(np.linalg.inv(P), A), P)
print(D)

[2. 3.]
[[0.         0.70710678]
 [1.         0.70710678]]
[[2. 0.]
 [0. 3.]]


In [51]:
import numpy as np
 
# 例題の行列
A = np.array([[5, 2],
              [2, 5]])
 
# 固有値と固有ベクトルを求める。
eig, P = np.linalg.eigh(A)
print(eig)
print(P)
print(2*P/np.sqrt(2))
P = 2*P/np.sqrt(2)
P = np.array([[1.,  1.],
 [ 1.,  -1.]])
print(P) 
print(np.linalg.inv(P)) 
# 対角化
D = np.dot(np.dot(np.linalg.inv(P), A), P)
print(D)

[3. 7.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[[-1.  1.]
 [ 1.  1.]]
[[ 1.  1.]
 [ 1. -1.]]
[[ 0.5  0.5]
 [ 0.5 -0.5]]
[[7. 0.]
 [0. 3.]]


https://watlab-blog.com/2019/06/27/linalg-diagonalization/

In [32]:
import numpy as np
 
# 例題の行列
A = np.array([[1, 3],
              [2, 4]])
 
# 固有値と固有ベクトルを求める。
eig, P = np.linalg.eigh(A)
print(eig)
print(P)
 
# 対角化
D = np.dot(np.dot(np.linalg.inv(P), A), P)
print(D)

[0. 5.]
[[-0.89442719  0.4472136 ]
 [ 0.4472136   0.89442719]]
[[-0.4 -0.8]
 [ 0.2  5.4]]
