In [1]:
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    #print("shape: " + str(x.shape))
    print("")


array([[0.1],
       [0.2]])

In [6]:
## 試してみよう_配列の初期化
W = np.zeros(2)
W

array([0., 0.])

In [40]:
W = np.zeros((2,2))
W

array([[0., 0.],
       [0., 0.]])

In [7]:
W = np.ones(2)
W

array([1., 1.])

In [8]:
W = np.random.rand(2)
W

array([0.54148067, 0.07548586])

In [9]:
W = np.random.randint(5, size=(2))
W

array([3, 4])

In [12]:
## 試してみよう_数値の初期化
b = np.random.rand() # 0~1のランダム数値
b

0.8354818515822825

In [13]:
b = np.random.rand() * 10 -5  # -5~5のランダム数値
b

3.823689988886631

In [15]:
## 試してみよう_配列の初期化
#W = np.zeros((4,3))
#W = np.ones((4,3))
#W = np.random.rand(4,3)
W = np.random.randint(5, size=(4,3))
W

array([[2, 1, 0],
       [2, 0, 4],
       [2, 0, 0],
       [3, 3, 0]])

In [18]:
W = np.random.randint(5, size=(4,3,2))
W

array([[[0, 0],
        [2, 1],
        [1, 4]],

       [[4, 0],
        [4, 3],
        [2, 2]],

       [[1, 1],
        [0, 4],
        [0, 0]],

       [[4, 2],
        [0, 2],
        [0, 4]]])

In [11]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3], 
    [0.2, 0.3, 0.4], 
    [0.3, 0.4, 0.5],
    [0.4, 0.5, 0.6]
])



print_vec("重み", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)


#  総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1 0.2 0.3]
 [0.2 0.3 0.4]
 [0.3 0.4 0.5]
 [0.4 0.5 0.6]]

*** バイアス ***
[0.1 0.2 0.3]

*** 入力 ***
[ 1.  5.  2. -1.]

*** 総入力 ***
[1.4 2.2 3. ]

*** 中間層出力 ***
[0.80218389 0.90024951 0.95257413]



In [ ]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]
    ])
    network['W3'] = np.array([
        [0.1, 0.3],
        [0.2, 0.4]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2])
    network['b3'] = np.array([1, 2])

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", z1)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

In [28]:
#試してみよう
#_各パラメータのshapeを表示
#_ネットワークの初期値ランダム生成

# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    network['W1'] = np.random.rand(2,3)

    network['W2'] = np.random.rand(2,3)

    network['W3'] = np.random.rand(2,2)

    network['b1'] = np.random.rand(3)

    network['b2'] = np.random.rand(2)

    network['b3'] = np.random.rand(2)


    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network
_ = init_network()

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.96544049 0.385645   0.17317617]
 [0.38854249 0.92441596 0.84815064]]

*** 重み2 ***
[[0.66820091 0.39132621 0.70610773]
 [0.53545705 0.08078833 0.15946247]]

*** 重み3 ***
[[0.09585375 0.84790356]
 [0.10484821 0.5860705 ]]

*** バイアス1 ***
[0.58060661 0.62775655 0.48397374]

*** バイアス2 ***
[0.08357558 0.33650387]

*** バイアス3 ***
[0.09495503 0.52524466]



In [32]:
# ウェイトとバイアスを設定
# ネートワークを作成
def init_network(input_layer_size, hidden_layer_size, output_layer_size):
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size, output_layer_size)
    network['b1'] = np.random.rand(hidden_layer_size)
    network['b2'] = np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

In [35]:
# 回帰
# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

input_layer_size = 3
hidden_layer_size= 5
output_layer_size = 4

# 入力値
x = np.array([1., 2.,3.])
network =  init_network(input_layer_size, hidden_layer_size, output_layer_size)
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4.,6.,8.])
# 誤差
loss = functions.mean_squared_error(d, y)
## 表示
print("\n##### 結果表示 #####")
print("input_layer_size", input_layer_size)
print("hidden_layer_size", hidden_layer_size)
print("output_layer_size", output_layer_size)

print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.5652631  0.28353574 0.88268301 0.63577038 0.09303166]
 [0.03107736 0.09090869 0.99950548 0.62006438 0.35314604]
 [0.82096514 0.88628879 0.4981184  0.18285504 0.95063937]]

*** 重み2 ***
[[0.18077822 0.79118166 0.51770001 0.19805648]
 [0.28384155 0.16568689 0.95667365 0.76275759]
 [0.32746294 0.49277979 0.16328018 0.33950754]
 [0.5468609  0.84949667 0.85570513 0.72745066]
 [0.4587165  0.93671639 0.90812593 0.31111512]]

*** バイアス1 ***
[0.68653777 0.50435753 0.17506018 0.20176283 0.13180406]

*** バイアス2 ***
[0.44778459 0.13370722 0.75653756 0.40155721]

##### 順伝播開始 #####
*** 総入力1 ***
[3.77685103 3.62857701 4.55110937 2.6262271  3.78304591]

*** 中間層出力1 ***
[3.77685103 3.62857701 4.55110937 2.6262271  3.78304591]

*** 総入力2 ***
[ 6.82234406 11.74039716 12.60904143  8.54986109]

*** 出力1 ***
[ 6.82234406 11.74039716 12.60904143  8.54986109]

出力合計: 18.365810424955626

##### 結果表示 #####
input_layer_size 3
hidden_layer_size 5
output_layer_size 4
*** 中間層出力 ***
[3

In [37]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう

input_layer_size = 5
hidden_layer_size= 10
output_layer_size = 1

# 入力値
x = np.array([1., 2.,3.,4.,5.])
# 目標出力
d = np.array([1])
network =  init_network(input_layer_size, hidden_layer_size, output_layer_size)
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print("input_layer_size", input_layer_size)
print("hidden_layer_size", hidden_layer_size)
print("output_layer_size", output_layer_size)

print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.97789581 0.45860308 0.74989297 0.07871868 0.26406475 0.01122758
  0.43668807 0.07820562 0.50879922 0.17139896]
 [0.73987446 0.18926488 0.78461447 0.17183914 0.21646273 0.26228592
  0.16061908 0.35431166 0.73388315 0.54189934]
 [0.38799073 0.65073276 0.48360831 0.11742747 0.62918706 0.89608263
  0.52152255 0.17830063 0.22384673 0.75002241]
 [0.03828214 0.35442607 0.66787206 0.79672686 0.26273609 0.39439729
  0.43102524 0.2333887  0.86380059 0.98133526]
 [0.59979884 0.81526975 0.96463694 0.72606666 0.25784201 0.66374238
  0.26467031 0.29827088 0.09374715 0.74246683]]

*** 重み2 ***
[[0.71289594]
 [0.6821429 ]
 [0.28538776]
 [0.30800099]
 [0.6327984 ]
 [0.72401949]
 [0.9329279 ]
 [0.4019296 ]
 [0.04974612]
 [0.20992624]]

*** バイアス1 ***
[0.58965844 0.4825029  0.16544438 0.85720463 0.42416301 0.64776345
 0.55633279 0.51510302 0.34501897 0.812026  ]

*** バイアス2 ***
[0.23120794]

##### 順伝播開始 #####
*** 総入力1 ***
[ 7.36339814  8.76588702 11.43006419  8.4491247

# 考察
`init_network`に対して、与えられた引数に従ってネットワークを初期化する修正を加えたことにより、ニューラルネットワークの構造および初期化処理のイメージをつかむことができた。また、順伝播処理のイメージを実装でつかむことができた。